# Imports

In [1]:
import pandas as pd
import numpy as np
import datetime

# Read and join datasets

In [2]:
df_1 = pd.read_csv('glassdoor_jobs.csv')
df_2 = pd.read_csv('glassdoor_jobs2.csv')

In [3]:
df = pd.concat([df_1, df_2], ignore_index=True)
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Unnamed: 0
0,Data Scientist- Streetsboro Ohio Office,$101K-$163K (Glassdoor est.),The Step2 Company is the largest American manu...,3.3,Step2\n3.3,"Streetsboro, OH",-1,1001 to 5000 Employees,1991,Company - Private,Consumer Products Manufacturing,Manufacturing,$100 to $500 million (USD),-1,NaN
1,Sr. Data Scientist - Model Governance,$101K-$163K (Glassdoor est.),General Summary:\n\nThe position plays a criti...,3.6,Elevate Credit\n3.6,"Addison, TX",-1,501 to 1000 Employees,2014,Company - Public,Lending,Finance,$100 to $500 million (USD),-1,NaN
2,Senior Principal Scientist,$101K-$163K (Glassdoor est.),"Senior Principal Scientist*\nMerrimack, NH*\nT...",3.3,Getinge Group\n3.3,"Merrimack, NH",-1,10000+ Employees,-1,Company - Public,Health Care Products Manufacturing,Manufacturing,$10+ billion (USD),-1,NaN
3,Semantic Data Modeler and Engineer,$101K-$163K (Glassdoor est.),Semantic Data Modeler and Engineer\n\nTucson E...,2.8,"Tucson Embedded Systems, Inc.\n2.8",Alabama,-1,51 to 200 Employees,1997,Company - Private,Enterprise Software & Network Solutions,Information Technology,$10 to $25 million (USD),-1,NaN
4,Certified Lab Scientist or Certified Lab Tech,$101K-$163K (Glassdoor est.),Prairie Ridge Health is looking for a team mem...,2.0,Prairie Ridge Health\n2.0,"Columbus, WI",-1,51 to 200 Employees,-1,Hospital,-1,-1,Less than $1 million (USD),-1,NaN

In [25]:
df.dtypes

Job Title             object
Salary Estimate       object
Job Description       object
Rating               float64
Company Name          object
Location              object
Headquarters           int64
Size                  object
Founded                int64
Type of ownership     object
Industry              object
Sector                object
Revenue               object
Competitors            int64
Unnamed: 0           float64
dtype: object

# Dataset cleaning

In [4]:
df = df[df['Salary Estimate'] != '-1']

In [5]:
salary = df['Salary Estimate'].apply(lambda x: x.split(' ')[0])
salary[:5]

0    $101K-$163K
1    $101K-$163K
2    $101K-$163K
3    $101K-$163K
4    $101K-$163K
Name: Salary Estimate, dtype: object

In [6]:
minus_Kd = salary.apply(lambda x: x.replace('K', ' ').replace('$', ' '))
minus_Kd[:5]

0     101 - 163
1     101 - 163
2     101 - 163
3     101 - 163
4     101 - 163
Name: Salary Estimate, dtype: object

In [7]:
work_h_per_year = 2000

min_hourly = []
max_hourly = []
for x in minus_Kd:
    lower_wage = (int(x.split('-')[0])*1000)/work_h_per_year
    upper_wage = (int(x.split('-')[1])*1000)/work_h_per_year
    min_hourly.append(lower_wage)
    max_hourly.append(upper_wage)

min_hourly[:5]

[50.5, 50.5, 50.5, 50.5, 50.5]

In [8]:
df['Min_salary_hourly'] = min_hourly
df['Max_salary_hourly'] = max_hourly

In [9]:
df['Min_salary'] = minus_Kd.apply(lambda x: int(x.split('-')[0]))
df['Max_salary'] = minus_Kd.apply(lambda x: int(x.split('-')[1]))
df['Avg_salary'] = (df.Min_salary + df.Max_salary)/2

In [10]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Unnamed: 0,Min_salary_hourly,Max_salary_hourly,Min_salary,Max_salary,Avg_salary
0,Data Scientist- Streetsboro Ohio Office,$101K-$163K (Glassdoor est.),The Step2 Company is the largest American manu...,3.3,Step2\n3.3,"Streetsboro, OH",-1,1001 to 5000 Employees,1991,Company - Private,Consumer Products Manufacturing,Manufacturing,$100 to $500 million (USD),-1,NaN,50.5,81.5,101,163,132.0
1,Sr. Data Scientist - Model Governance,$101K-$163K (Glassdoor est.),General Summary:\n\nThe position plays a criti...,3.6,Elevate Credit\n3.6,"Addison, TX",-1,501 to 1000 Employees,2014,Company - Public,Lending,Finance,$100 to $500 million (USD),-1,NaN,50.5,81.5,101,163,132.0
2,Senior Principal Scientist,$101K-$163K (Glassdoor est.),"Senior Principal Scientist*\nMerrimack, NH*\nT...",3.3,Getinge Group\n3.3,"Merrimack, NH",-1,10000+ Employees,-1,Company - Public,Health Care Products Manufacturing,Manufacturing,$10+ billion (USD),-1,NaN,50.5,81.5,101,163,132.0
3,Semantic Data Modeler and Engineer,$101K-$163K (Glassdoor est.),Semantic Data Modeler and Engineer\n\nTucson E...,2.8,"Tucson Embedded Systems, Inc.\n2.8",Alabama,-1,51 to 200 Employees,1997,Company - Private,Enterprise Software & Network Solutions,Information Technology,$10 to $25 million (USD),-1,NaN,50.5,81.5,101,163,132.0
4,Certified Lab Scientist or Certified Lab Tech,$101K-$163K (Glassdoor est.),Prairie Ridge Health is looking for a team mem...,2.0,Prairie Ridge Health\n2.0,"Columbus, WI",-1,51 to 200 Employees,-1,Hospital,-1,-1,Less than $1 million (USD),-1,NaN,50.5,81.5,101,163,132.0

In [11]:
columns = df.columns.tolist()
columns

['Job Title',
 'Salary Estimate',
 'Job Description',
 'Rating',
 'Company Name',
 'Location',
 'Headquarters',
 'Size',
 'Founded',
 'Type of ownership',
 'Industry',
 'Sector',
 'Revenue',
 'Competitors',
 'Unnamed: 0',
 'Min_salary_hourly',
 'Max_salary_hourly',
 'Min_salary',
 'Max_salary',
 'Avg_salary']

In [12]:
df = df[['Job Title','Job Description','Rating','Company Name','Location','Headquarters','Size','Founded',
'Type of ownership','Industry','Sector','Revenue','Min_salary_hourly','Max_salary_hourly','Min_salary','Max_salary','Avg_salary']]

In [13]:
df['Company_name_txt'] = df.apply(lambda x: x['Company Name'] if x['Rating']<0 else x['Company Name'][:-3], axis=1)

In [14]:
df['Company_name_txt'] = df.apply(lambda x: x['Company_name_txt'][:-1] if x['Company_name_txt'].endswith('\n') else x['Company_name_txt'], axis=1)

In [15]:
df['Job state'] = df['Location'].apply(lambda x: x.split(',')[1] if ',' in x else x)

In [16]:
df['Job state'].value_counts()

 CA              22
 OH               9
 MD               7
 WI               6
 VA               5
 TX               5
 MA               4
 CO               4
 AL               4
 ID               4
 NH               3
 DC               3
 IL               2
 PR               2
 FL               2
 MO               2
 ND               2
 NC               2
 GA               2
Alabama           2
 WA               2
 MN               1
 ME               1
 MS               1
United States     1
 NY               1
 IN               1
Name: Job state, dtype: int64

In [17]:
df['Job state'].replace('United States','-',inplace=True)
df['Job state'].value_counts()

 CA        22
 OH         9
 MD         7
 WI         6
 VA         5
 TX         5
 MA         4
 CO         4
 AL         4
 ID         4
 NH         3
 DC         3
 IL         2
 PR         2
 FL         2
 MO         2
 ND         2
 NC         2
 GA         2
Alabama     2
 WA         2
 MN         1
 MS         1
 ME         1
 NY         1
-           1
 IN         1
Name: Job state, dtype: int64

In [18]:
df['Headquarters'].value_counts()

-1    100
Name: Headquarters, dtype: int64

In [19]:
df.drop(['Headquarters'], axis=1, inplace=True)
df.drop(['Company Name'], axis=1, inplace=True)

,Job Title,Job Description,Rating,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_salary_hourly,Max_salary_hourly,Min_salary,Max_salary,Avg_salary,Company_name_txt,Job state
0,Data Scientist- Streetsboro Ohio Office,The Step2 Company is the largest American manu...,3.3,"Streetsboro, OH",1001 to 5000 Employees,1991,Company - Private,Consumer Products Manufacturing,Manufacturing,$100 to $500 million (USD),50.5,81.5,101,163,132.0,Step2,OH
1,Sr. Data Scientist - Model Governance,General Summary:\n\nThe position plays a criti...,3.6,"Addison, TX",501 to 1000 Employees,2014,Company - Public,Lending,Finance,$100 to $500 million (USD),50.5,81.5,101,163,132.0,Elevate Credit,TX
2,Senior Principal Scientist,"Senior Principal Scientist*\nMerrimack, NH*\nT...",3.3,"Merrimack, NH",10000+ Employees,-1,Company - Public,Health Care Products Manufacturing,Manufacturing,$10+ billion (USD),50.5,81.5,101,163,132.0,Getinge Group,NH
3,Semantic Data Modeler and Engineer,Semantic Data Modeler and Engineer\n\nTucson E...,2.8,Alabama,51 to 200 Employees,1997,Company - Private,Enterprise Software & Network Solutions,Information Technology,$10 to $25 million (USD),50.5,81.5,101,163,132.0,"Tucson Embedded Systems, Inc.",Alabama
4,Certified Lab Scientist or Certified Lab Tech,Prairie Ridge Health is looking for a team mem...,2.0,"Columbus, WI",51 to 200 Employees,-1,Hospital,-1,-1,Less than $1 million (USD),50.5,81.5,101,163,132.0,Prairie Ridge Health,WI

In [20]:
now = datetime.datetime.now()
df['Company Age'] = df.Founded.apply(lambda x: x if x<1 else now.year-x)

In [21]:
df['Job Description'][0]

"The Step2 Company is the largest American manufacturer of preschool and toddler toys and one of the world’s largest rotational molders of plastics. It’s our mission to be the leading innovator of children's products that build imaginations and enrich the family's celebration of childhood.\n\nStep2 proudly employs moms, dads, grandparents, aunts, uncles and everyone in between. We offer an environment of fun and hard work. Our mission of bringing families together isn’t just for our customers. The Step2 family starts with our employees and we’re excited that you’re interested in joining our team!\n\nPRIMARY FUNCTION: Reporting to the IT Director, and in close collaboration FP&A, the Data Scientist will support our product, sales, operations, and marketing teams with insights gained from analyzing company data. The ideal candidate is adept at using large data sets to find opportunities for product and process optimization and using models to test the effectiveness of different courses of action. They must have strong experience using a variety of data mining/data analysis methods, using a variety of data tools, building and implementing models, using/creating algorithms and creating/running simulations. They must have a proven ability to drive business results with their data-based insights. They must be comfortable working with a wide range of stakeholders and functional teams. The right candidate will have a passion for discovering solutions hidden in large data sets and working with stakeholders to improve business outcomes.\n\nSPECIFIC DUTIES/ACCOUNTABILITIES:\nResearch and develop statistical learning models for data analysis\nKeep up-to-date with latest technology trends\nCommunicate results and ideas to key decision makers\nImplement new statistical or other mathematical methodologies as needed for specific models or analysis\nOptimize joint development efforts through appropriate database use and project design\nFunctions as Oracle subject matter expert and ensures end users are properly trained to use system and reports appropriately; troubleshoots issues.\nServes as the System Administrator for the Daily Operating System (D.O.S.) Report and supporting network.\nEnsures functionality and accuracy of reports which make up the D.O.S. report (i.e. Mold Placement Master, Mold Placement Report, Attendance Rosters).\nKeeps D.O.S. supporting data updated (i.e. labor standards, NSP pricing, tooling information, goals, etc.)\nData mines and analyzes data from Oracle to provide user-friendly ad-hoc reports as request by various departments and upper level management.\nDesign and create a data repository to achieve the above objectives\nBASIC QUALIFICATIONS:\n5-7 years of experience manipulating data sets and building statistical models, a degree in Statistics, Mathematics, Computer Science or another quantitative field.\nExperience working with and creating data architectures.\nKnowledge of advanced statistical techniques and concepts (regression, properties of distributions, statistical tests and proper usage, etc.) and experience with applications.\nExcellent written and verbal communication skills for coordinating across teams.\nA drive to learn and master new technologies and techniques.\nExperience creating and using advanced machine learning algorithms and statistics: regression, simulation, scenario analysis, modeling, clustering, decision trees, neural networks, etc.\nExperience analyzing data from 3rd party providers: Google Analytics, Site Catalyst, Adwords, Content Analytics, Facebook Insights, etc.\n\n\nADDITIONAL QUALIFICATIONS:\nExcellent project management skills\nAbility to explain complex issues clearly and succinctly\nEffectively summarizes and communicates results\nAbility to forecast potential problems and pitfalls\nWhat are the perks?\n· Parental Leave\n· 401k with Employer Match\n· Tuition Assistance\n· Company Paid Life& Disability Insurance\n· Adoption Assistance\n· Medical, Dental and Vision\n· Premium FREE Medical Plan\n· Employee Discount\n· 10 Paid Holidays\n· Advancement Opportunities\nJoin our family!\n\nApply today or text Step2Jobs to 97211 to connect with a recruiter.\n\nStep2 is an Equal Opportunity Employer\n\n\n\nStep2 is an Equal Opportunity Employer"

In [22]:
skills = ['python', 'r studio', 'spark', 'aws', 'matlab','hadoop']

for skill in skills:
    df[skill] = df['Job Description'].apply(lambda x: 1 if skill in x.lower() else 0)

In [23]:
skills_summary = {}
for skill in skills:
    temp = df[skill].value_counts()[1]
    skills_summary[skill] = temp


skills_summary

{'python': 47, 'r studio': 2, 'spark': 5, 'aws': 19, 'matlab': 9, 'hadoop': 8}

In [24]:
df['Size'] = df['Size'].apply(lambda x: x.replace('to', '-') if 'to' in x else x)
df['Size'] = df['Size'].apply(lambda x: x.replace('Employees', '') if 'Employees' in x else x)
df.rename(columns={"Size": "Company Size"}, inplace=True)

# Extracting new dataset as csv file

In [25]:
df_out = df
df_out.to_csv('Salary_data_cleaned.csv', index=False)

In [56]:
clean_df = pd.read_csv('Salary_data_cleaned.csv')
clean_df.head()

,Job Title,Job Description,Rating,Location,Company Size,Founded,Type of ownership,Industry,Sector,Revenue,Min_salary_hourly,Max_salary_hourly,Min_salary,Max_salary,Avg_salary,Company_name_txt,Job state,Company Age,python,r studio,spark,aws,matlab,hadoop
0,Data Scientist- Streetsboro Ohio Office,The Step2 Company is the largest American manu...,3.3,"Streetsboro, OH",1001 - 5000,1991,Company - Private,Consumer Products Manufacturing,Manufacturing,$100 to $500 million (USD),50.5,81.5,101,163,132.0,Step2,OH,29,0,0,0,0,0,0
1,Sr. Data Scientist - Model Governance,General Summary:\n\nThe position plays a criti...,3.6,"Addison, TX",501 - 1000,2014,Company - Public,Lending,Finance,$100 to $500 million (USD),50.5,81.5,101,163,132.0,Elevate Credit,TX,6,1,0,0,0,1,0
2,Senior Principal Scientist,"Senior Principal Scientist*\nMerrimack, NH*\nT...",3.3,"Merrimack, NH",10000+,-1,Company - Public,Health Care Products Manufacturing,Manufacturing,$10+ billion (USD),50.5,81.5,101,163,132.0,Getinge Group,NH,-1,0,0,0,0,0,0
3,Semantic Data Modeler and Engineer,Semantic Data Modeler and Engineer\n\nTucson E...,2.8,Alabama,51 - 200,1997,Company - Private,Enterprise Software & Network Solutions,Information Technology,$10 to $25 million (USD),50.5,81.5,101,163,132.0,"Tucson Embedded Systems, Inc.",Alabama,23,0,0,0,0,0,0
4,Certified Lab Scientist or Certified Lab Tech,Prairie Ridge Health is looking for a team mem...,2.0,"Columbus, WI",51 - 200,-1,Hospital,-1,-1,Less than $1 million (USD),50.5,81.5,101,163,132.0,Prairie Ridge Health,WI,-1,0,0,0,0,0,0
5,Digital Pathology Scientist,Digital Pathology Scientist *\nDescription*\nM...,3.5,"Lake Forest, CA",1 - 50,-1,Company - Private,-1,-1,$1 to $5 million (USD),50.5,81.5,101,163,132.0,Mosaic Laboratories,CA,-1,0,0,0,0,0,0
6,Research Scientist - Lactic Solutions,The *Research Scientist - Lactic Solutions *wi...,3.4,"Lebanon, NH",1001 - 5000,1895,Company - Private,Food & Beverage Manufacturing,Manufacturing,Unknown / Non-Applicable,50.5,81.5,101,163,132.0,Lallemand,NH,125,0,0,0,0,0,0
7,Research Scientist - Plant Transformation,Living Carbon is a pre-launch public benefit c...,3.9,"San Francisco, CA",1 - 50,-1,Other Organization,-1,-1,Less than $1 million (USD),50.5,81.5,101,163,132.0,Living Carbon,CA,-1,0,0,0,0,0,0
8,R&D Scientist,Our Research and Development department is on ...,4.3,"Twin Falls, ID",1001 - 5000,2005,Company - Private,Food & Beverage Manufacturing,Manufacturing,$1 to $2 billion (USD),50.5,81.5,101,163,132.0,Chobani,ID,15,0,0,0,1,0,0
9,HCM Data Analyst,Any qualified individual with a disability who...,3.2,"Mobile, AL",1001 - 5000,1988,Company - Public,Industrial Manufacturing,Manufacturing,$1 to $2 billion (USD),50.5,81.5,101,163,132.0,Austal USA,AL,32,0,0,0,0,0,0
10,Manufacturing Scientist,Biomerica Corporation focusing on the research...,2.5,"Irvine, CA",1 - 50,-1,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$5 to $10 million (USD),50.5,81.5,101,163,132.0,Biomerica,CA,-1,0,0,0,0,0,0
11,Fungal Scientist,Job Description/Primary Duties and Responsibil...,2.5,"Aberdeen Proving Ground, MD",1 - 50,1986,Company - Private,Consulting,Business Services,$10 to $25 million (USD),50.5,81.5,101,163,132.0,"General Technical Services, LLC and Fibertek, ...",MD,34,0,0,0,0,0,0
12,"Data Scientist, Medical Diagnostics",_*The Company*_\nThe world is facing a medical...,1.0,"Mountain View, CA",1 - 50,-1,Company - Private,-1,-1,Less than $1 million (USD),50.5,81.5,101,163,132.0,Specific Diagnostics,CA,-1,1,0,0,0,0,0
13,Data Analyst,PerBlue is looking for an aspiring Data Analys...,4.3,"Madison, WI",51 - 200,2010,Company - Private,Video Games,Media,Unknown / Non-Applicable,50.5,81.5,101,163,132.0,PerBlue,WI,10,1,0,0,0,0,0
14,Cell Line Development Scientist,"Job Title: Scientist, Cell Line Development*\n...",3.2,"Chesterfield, MO",201 - 500,1996,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),50.5,81.5,101,163,132.0,"Integrated Resources, Inc",MO,24,0,0,0,0,0,0
15,Scientist,Why Join Revenue Analytics?\nBecause you have ...,4.1,"Atlanta, GA",51 - 200,2005,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),50.5,81.5,101,163,132.0,Revenue Analytics,GA,15,1,0,0,0,0,0
16,Scientific Data Analyst,"Scientific Data Analyst\n\nMelbourne, FL\n\nAb...",3.7,"Melbourne, FL",501 - 1000,1969,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),50.5,81.5,101,163,132.0,"ENSCO, Inc.",FL,51,1,0,0,0,1,0
17,Process Development Scientist 29981- Validatio...,Education: *\n*Doctorate degree or Master’s de...,3.7,"Juncos, PR",Unknown,-1,Company - Private,-1,-1,Less than $1 million (USD),50.5,81.5,101,163,132.0,CIS International LLC,PR,-1,0,0,0,0,0,0
18,Senior Genomic Data Scientist,GeneDx is seeking a Senior Genomic Data Scient...,2.8,"Gaithersburg, MD",201 - 500,-1,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10 to $25 million (USD),50.5,81.5,101,163,132.0,GeneDx,MD,-1,1,0,0,1,0,0
19,Data Scientist,Description\n\nPosition at Homes.com\n\nHomes....,4.1,"Norfolk, VA",201 - 500,1998,Company - Private,Real Estate,Real Estate,$50 to $100 million (USD),50.5,81.5,101,163,132.0,Homes.com,VA,22,1,0,0,0,0,0
20,Data Analyst,Breckenridge Grand Vacations (BGV) is seeking ...,4.3,"Breckenridge, CO",501 - 1000,1984,Company - Private,"Hotels, Motels, & Resorts",Travel & Tourism,$10 to $25 million (USD),50.5,81.5,101,163,132.0,Breckenridge Grand Vacations,CO,36,1,0,0,0,1,0
21,Sr. DATA SCIENTIST,Title: Sr. Data Scientist\n\nCompany: Samsung ...,3.7,"Mountain View, CA",1001 - 5000,1988,Subsidiary or Business Segment,Computer Hardware & Software,Information Technology,$50 to $100 million (USD),50.5,81.5,101,163,132.0,Samsung Research America,CA,32,1,0,1,1,0,0
22,Supply Chain Solution - Data Scientist,*CURRENT EMPLOYEES :\nPlease click here to be ...,3.8,"Austin, TX",10000+,1969,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$10+ billion (USD),50.5,81.5,101,163,132.0,Flex,TX,51,1,0,0,1,0,1
23,Population Health Data Analyst,Job Summary\n\nThe Healthcare Intelligence Ana...,2.9,"Fargo, ND",501 - 1000,1940,Company - Private,Insurance Carriers,Insurance,Less than $1 million (USD),50.5,81.5,101,163,132.0,Blue Cross Blue Shield of North Dakota,ND,80,0,0,0,0,0,0
24,Scientist,ArsenalBio’s mission is to develop efficacious...,5.0,"South San Francisco, CA",51 - 200,2019,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,50.5,81.5,101,163,132.0,Arsenal Biosciences,CA,1,0,0,0,0,0,0
25,"Data Scientist, Health Economics & Advanced An...",Overview\n\n\nAvalere Health is seeking a Data...,3.2,"Washington, DC",201 - 500,2000,Company - Public,Consulting,Business Services,Less than $1 million (USD),50.5,81.5,101,163,132.0,Avalere Health,DC,20,1,0,0,0,0,0
26,Senior Research Statistician- Data Scientist,Acuity is seeking a Senior Research Statistici...,4.9,"Sheboygan, WI",1001 - 5000,1925,Company - Private,Insurance Carriers,Insurance,$1 to $2 billion (USD),50.5,81.5,101,163,132.0,Acuity Insurance,WI,95,0,0,0,0,0,0
27,Senior Analyst/Data Scientist,At Edmunds were driven to make car buying easi...,3.6,"Santa Monica, CA",501 - 1000,1966,Company - Private,Internet,Information Technology,$100 to $500 million (USD),50.5,81.5,101,163,132.0,Edmunds.com,CA,54,1,0,0,1,0,0
28,Data Analyst,"At TrialCard, our passion is success - success...",3.3,"Morrisville, NC",1001 - 5000,2001,Company - Private,Advertising & Marketing,Business Services,$50 to $100 million (USD),50.5,81.5,101,163,132.0,TrialCard,NC,19,0,0,0,0,0,0
29,Data Analyst,Healthgrades is focused on providing trusted i...,2.9,"Denver, CO",501 - 1000,1998,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,50.5,81.5,101,163,132.0,Healthgrades,CO,22,0,0,0,0,0,0
30,"Data Scientist, Product Development",Spokeo is a people search engine that both enl...,3.4,"Pasadena, CA",51 - 200,2006,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,27.5,45.5,55,91,73.0,Spokeo,CA,14,1,0,1,0,0,1
31,Marketing Analytics Data Scientist,Tinder brings people together. With tens of mi...,3.9,"Los Angeles, CA",201 - 500,2012,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,27.5,45.5,55,91,73.0,Tinder,CA,8,1,0,0,0,0,0
32,Senior Genomic Data Scientist,GeneDx is seeking a Senior Genomic Data Scient...,2.8,"Gaithersburg, MD",201 - 500,-1,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10 to $25 million (USD),27.5,45.5,55,91,73.0,GeneDx,MD,-1,1,0,0,1,0,0
33,DATA SCIENTIST,JOB SUMMARY\n\nThe position will focus on buil...,3.8,"Quincy, IL",1001 - 5000,1875,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),27.5,45.5,55,91,73.0,Blessing Hospital,IL,145,1,0,0,1,1,0
34,Marketing Data Analyst,Overview:\nCan you work in a relationship with...,4.2,"Chubbuck, ID",1001 - 5000,1940,Nonprofit Organization,Banks & Credit Unions,Finance,$50 to $100 million (USD),27.5,45.5,55,91,73.0,Idaho Central Credit Union,ID,80,0,0,0,0,0,0
35,Business Intelligence Analyst,"Join a small, dynamic data-warehouse (DWH) tea...",2.2,"Cleveland, OH",201 - 500,-1,Company - Public,Other Retail Stores,Retail,Unknown / Non-Applicable,27.5,45.5,55,91,73.0,AmeriMark Direct,OH,-1,0,0,0,0,0,0
36,Electromagnetics Scientist,Riverside Research has an immediate opening in...,3.4,"Wright Patterson AFB, OH",501 - 1000,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),27.5,45.5,55,91,73.0,Riverside Research,OH,53,1,0,0,0,1,0
37,Data Scientist,STRATACACHE provides salable customer experien...,3.5,"Dayton, OH",201 - 500,1999,Company - Private,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),27.5,45.5,55,91,73.0,STRATACACHE,OH,21,1,0,0,0,0,1
38,Data Scientist,Job Description:\n\nMetron is seeking talented...,3.0,"Reston, VA",51 - 200,-1,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,$25 to $50 million (USD),27.5,45.5,55,91,73.0,"Metron, Inc.",VA,-1,1,0,0,0,0,0
39,Project Manager/Senior Scientist,Project Manager/Senior Scientist*\nBoyle Assoc...,4.5,"Portland, ME",51 - 200,-1,Company - Private,Consulting,Business Services,$10 to $25 million (USD),27.5,45.5,55,91,73.0,"Boyle Associates, a subsidiary of CEA",ME,-1,0,0,0,0,0,0
40,V&S Business Data Analyst,"Sony Electronics, Inc. look for the risk-taker...",4.0,"San Diego, CA",10000+,1946,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$2 to $5 billion (USD),27.5,45.5,55,91,73.0,Sony Electronics,CA,74,0,0,0,0,0,0
41,Junior Data Scientist,What Great Looks Like In This Role\n\nOur idea...,3.7,"Amherst, MA",5001 - 10000,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),27.5,45.5,55,91,73.0,MassMutual,MA,169,1,0,0,0,0,0
42,Business Intelligence Analyst,Blucora has a bold aspiration: we are committe...,3.3,"Dallas, TX",501 - 1000,1996,Company - Public,Financial Transaction Processing,Finance,$500 million to $1 billion (USD),27.5,45.5,55,91,73.0,Blucora,TX,24,0,0,0,0,0,0
43,Data Architect/Scientist,Senior Member of Technical Staff – DATA ARCHIT...,4.1,"Seattle, WA",1001 - 5000,1981,Subsidiary or Business Segment,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),27.5,45.5,55,91,73.0,Wind River,WA,39,1,0,0,0,0,1
44,Data Analyst,Big Huge Games is looking for a qualified Data...,4.9,"Timonium, MD",51 - 200,2013,Subsidiary or Business Segment,Video Games,Media,Unknown / Non-Applicable,27.5,45.5,55,91,73.0,Big Huge Games,MD,7,0,1,0,0,0,0
45,Data Science Engineer Full Stack - AI,Data Science Engineer Full Stack - AI\n\nOverv...,2.8,United States,51 - 200,2000,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),27.5,45.5,55,91,73.0,BryterCX,-,20,1,0,1,0,0,0
46,Marketing Data Analyst,College bachelor’s degree required. Major in B...,4.3,"Jackson, MS",501 - 1000,1946,Company - Private,Insurance Carriers,Insurance,$1 to $2 billion (USD),27.5,45.5,55,91,73.0,Southern Farm Bureau Life,MS,74,0,0,0,0,0,0
47,"Data Scientist, Machine Learning","Job Description\n\nAt Shipt, we are transformi...",3.6,"Birmingham, AL",1001 - 5000,2014,Subsidiary or Business Segment,Consumer Product Rental,Consumer Services,Unknown / Non-Applicable,27.5,45.5,55,91,73.0,Shipt,AL,6,1,0,0,1,0,0
48,"Data Scientist, Cloud Business Operations",53303\n\nAbout NetApp\n\nNetApp provides softw...,3.8,"Sunnyvale, CA",10000+,1992,Company - Public,Enterprise Software & Network Solutions,Information Technology,$5 to $10 billion (USD),27.5,45.5,55,91,73.0,NetApp,CA,28,0,0,0,1,0,0
49,Internship - Data Science,Internship - Data Science\n\nJob Details\nLeve...,2.6,"Washington, DC",51 - 200,1991,Nonprofit Organization,Membership Organizations,Business Services,$5 to $10 million (USD),27.5,45.5,55,91,73.0,National League of Cities,DC,29,1,0,0,0,0,0
50,Data Scientist,Description\n\nPosition at Homes.com\n\nHomes....,4.1,"Norfolk, VA",201 - 500,1998,Company - Private,Real Estate,Real Estate,$50 to $100 million (USD),35.0,47.5,70,95,82.5,Homes.com,VA,22,1,0,0,0,0,0
51,Data Scientist- Streetsboro Ohio Office,The Step2 Company is the largest American manu...,3.3,"Streetsboro, OH",1001 - 5000,1991,Company - Private,Consumer Products Manufacturing,Manufacturing,$100 to $500 million (USD),35.0,47.5,70,95,82.5,Step2,OH,29,0,0,0,0,0,0
52,Semantic Data Modeler and Engineer,Semantic Data Modeler and Engineer\n\nTucson E...,2.8,Alabama,51 - 200,1997,Company - Private,Enterprise Software & Network Solutions,Information Technology,$10 to $25 million (USD),35.0,47.5,70,95,82.5,"Tucson Embedded Systems, Inc.",Alabama,23,0,0,0,0,0,0
53,Digital Pathology Scientist,Digital Pathology Scientist *\nDescription*\nM...,3.5,"Lake Forest, CA",1 - 50,-1,Company - Private,-1,-1,$1 to $5 million (USD),35.0,47.5,70,95,82.5,Mosaic Laboratories,CA,-1,0,0,0,0,0,0
54,Certified Lab Scientist or Certified Lab Tech,Prairie Ridge Health is looking for a team mem...,2.0,"Columbus, WI",51 - 200,-1,Hospital,-1,-1,Less than $1 million (USD),35.0,47.5,70,95,82.5,Prairie Ridge Health,WI,-1,0,0,0,0,0,0
55,Manufacturing Scientist,Biomerica Corporation focusing on the research...,2.5,"Irvine, CA",1 - 50,-1,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$5 to $10 million (USD),35.0,47.5,70,95,82.5,Biomerica,CA,-1,0,0,0,0,0,0
56,Research Scientist - Lactic Solutions,The *Research Scientist - Lactic Solutions *wi...,3.4,"Lebanon, NH",1001 - 5000,1895,Company - Private,Food & Beverage Manufacturing,Manufacturing,Unknown / Non-Applicable,35.0,47.5,70,95,82.5,Lallemand,NH,125,0,0,0,0,0,0
57,R&D Scientist,Our Research and Development department is on ...,4.3,"Twin Falls, ID",1001 - 5000,2005,Company - Private,Food & Beverage Manufacturing,Manufacturing,$1 to $2 billion (USD),35.0,47.5,70,95,82.5,Chobani,ID,15,0,0,0,1,0,0
58,Research Scientist - Plant Transformation,Living Carbon is a pre-launch public benefit c...,3.9,"San Francisco, CA",1 - 50,-1,Other Organization,-1,-1,Less than $1 million (USD),35.0,47.5,70,95,82.5,Living Carbon,CA,-1,0,0,0,0,0,0
59,HCM Data Analyst,Any qualified individual with a disability who...,3.2,"Mobile, AL",1001 - 5000,1988,Company - Public,Industrial Manufacturing,Manufacturing,$1 to $2 billion (USD),35.0,47.5,70,95,82.5,Austal USA,AL,32,0,0,0,0,0,0
60,Field Scientist,Company Description*\nSGS is the world's leadi...,3.1,"Murdock, MN",10000+,1878,Company - Public,Consulting,Business Services,$5 to $10 billion (USD),35.0,47.5,70,95,82.5,SGS,MN,142,0,0,0,1,0,0
61,Fungal Scientist,Job Description/Primary Duties and Responsibil...,2.5,"Aberdeen Proving Ground, MD",1 - 50,1986,Company - Private,Consulting,Business Services,$10 to $25 million (USD),35.0,47.5,70,95,82.5,"General Technical Services, LLC and Fibertek, ...",MD,34,0,0,0,0,0,0
62,"Data Scientist, Medical Diagnostics",_*The Company*_\nThe world is facing a medical...,1.0,"Mountain View, CA",1 - 50,-1,Company - Private,-1,-1,Less than $1 million (USD),35.0,47.5,70,95,82.5,Specific Diagnostics,CA,-1,1,0,0,0,0,0
63,Process Development Scientist 29981- Validatio...,Education: *\n*Doctorate degree or Master’s de...,3.7,"Juncos, PR",Unknown,-1,Company - Private,-1,-1,Less than $1 million (USD),35.0,47.5,70,95,82.5,CIS International LLC,PR,-1,0,0,0,0,0,0
64,Cell Line Development Scientist,"Job Title: Scientist, Cell Line Development*\n...",3.2,"Chesterfield, MO",201 - 500,1996,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD),35.0,47.5,70,95,82.5,"Integrated Resources, Inc",MO,24,0,0,0,0,0,0
65,Data Analyst,PerBlue is looking for an aspiring Data Analys...,4.3,"Madison, WI",51 - 200,2010,Company - Private,Video Games,Media,Unknown / Non-Applicable,35.0,47.5,70,95,82.5,PerBlue,WI,10,1,0,0,0,0,0
66,Scientist,Why Join Revenue Analytics?\nBecause you have ...,4.1,"Atlanta, GA",51 - 200,2005,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),35.0,47.5,70,95,82.5,Revenue Analytics,GA,15,1,0,0,0,0,0
67,Scientific Data Analyst,"Scientific Data Analyst\n\nMelbourne, FL\n\nAb...",3.7,"Melbourne, FL",501 - 1000,1969,Company - Private,Aerospace & Defense,Aerospace & Defense,$100 to $500 million (USD),35.0,47.5,70,95,82.5,"ENSCO, Inc.",FL,51,1,0,0,0,1,0
68,Senior Genomic Data Scientist,GeneDx is seeking a Senior Genomic Data Scient...,2.8,"Gaithersburg, MD",201 - 500,-1,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10 to $25 million (USD),35.0,47.5,70,95,82.5,GeneDx,MD,-1,1,0,0,1,0,0
69,Data Analyst,Breckenridge Grand Vacations (BGV) is seeking ...,4.3,"Breckenridge, CO",501 - 1000,1984,Company - Private,"Hotels, Motels, & Resorts",Travel & Tourism,$10 to $25 million (USD),35.0,47.5,70,95,82.5,Breckenridge Grand Vacations,CO,36,1,0,0,0,1,0
70,Supply Chain Solution - Data Scientist,*CURRENT EMPLOYEES :\nPlease click here to be ...,3.8,"Austin, TX",10000+,1969,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$10+ billion (USD),35.0,47.5,70,95,82.5,Flex,TX,51,1,0,0,1,0,1
71,Scientist,ArsenalBio’s mission is to develop efficacious...,5.0,"South San Francisco, CA",51 - 200,2019,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,35.0,47.5,70,95,82.5,Arsenal Biosciences,CA,1,0,0,0,0,0,0
72,Food Scientist,"Location:\nMarlborough, Massachusetts, US\nJob...",3.8,"Marlborough, MA",1001 - 5000,1958,Company - Private,Food & Beverage Manufacturing,Manufacturing,Unknown / Non-Applicable,35.0,47.5,70,95,82.5,Ken's Foods,MA,62,0,0,0,0,0,0
73,Senior Research Statistician- Data Scientist,Acuity is seeking a Senior Research Statistici...,4.9,"Sheboygan, WI",1001 - 5000,1925,Company - Private,Insurance Carriers,Insurance,$1 to $2 billion (USD),35.0,47.5,70,95,82.5,Acuity Insurance,WI,95,0,0,0,0,0,0
74,Population Health Data Analyst,Job Summary\n\nThe Healthcare Intelligence Ana...,2.9,"Fargo, ND",501 - 1000,1940,Company - Private,Insurance Carriers,Insurance,Less than $1 million (USD),35.0,47.5,70,95,82.5,Blue Cross Blue Shield of North Dakota,ND,80,0,0,0,0,0,0
75,Sr. DATA SCIENTIST,Title: Sr. Data Scientist\n\nCompany: Samsung ...,3.7,"Mountain View, CA",1001 - 5000,1988,Subsidiary or Business Segment,Computer Hardware & Software,Information Technology,$50 to $100 million (USD),35.0,47.5,70,95,82.5,Samsung Research America,CA,32,1,0,1,1,0,0
76,Data Analyst,Healthgrades is focused on providing trusted i...,2.9,"Denver, CO",501 - 1000,1998,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,35.0,47.5,70,95,82.5,Healthgrades,CO,22,0,0,0,0,0,0
77,Senior Analyst/Data Scientist,At Edmunds were driven to make car buying easi...,3.6,"Santa Monica, CA",501 - 1000,1966,Company - Private,Internet,Information Technology,$100 to $500 million (USD),35.0,47.5,70,95,82.5,Edmunds.com,CA,54,1,0,0,1,0,0